// svalboard.js
//
////////////////////////////////////
//
//  Defaults for svalboard. When uploading incomplete 
//  .vil files that don't contain this extra data.
//
////////////////////////////////////

const SVALBOARD = {
 "cols" : 6,
 "combo_count" : 50,
 "combos" : [
   [ "KC_NO", "KC_NO", "KC_NO", "KC_NO", "KC_NO" ],
   [ "KC_NO", "KC_NO", "KC_NO", "KC_NO", "KC_NO" ],
   [ "KC_NO", "KC_NO", "KC_NO", "KC_NO", "KC_NO" ],
   [ "KC_NO", "KC_NO", "KC_NO", "KC_NO", "KC_NO" ],
   [ "KC_NO", "KC_NO", "KC_NO", "KC_NO", "KC_NO" ],
   [ "KC_NO", "KC_NO", "KC_NO", "KC_NO", "KC_NO" ],
   [ "KC_NO", "KC_NO", "KC_NO", "KC_NO", "KC_NO" ],
   [ "KC_NO", "KC_NO", "KC_NO", "KC_NO", "KC_NO" ],
   [ "KC_NO", "KC_NO", "KC_NO", "KC_NO", "KC_NO" ],
   [ "KC_NO", "KC_NO", "KC_NO", "KC_NO", "KC_NO" ],
   [ "KC_NO", "KC_NO", "KC_NO", "KC_NO", "KC_NO" ],
   [ "KC_NO", "KC_NO", "KC_NO", "KC_NO", "KC_NO" ],
   [ "KC_NO", "KC_NO", "KC_NO", "KC_NO", "KC_NO" ],
   [ "KC_NO", "KC_NO", "KC_NO", "KC_NO", "KC_NO" ],
   [ "KC_NO", "KC_NO", "KC_NO", "KC_NO", "KC_NO" ],
   [ "KC_NO", "KC_NO", "KC_NO", "KC_NO", "KC_NO" ],
   [ "KC_NO", "KC_NO", "KC_NO", "KC_NO", "KC_NO" ],
   [ "KC_NO", "KC_NO", "KC_NO", "KC_NO", "KC_NO" ],
   [ "KC_NO", "KC_NO", "KC_NO", "KC_NO", "KC_NO" ],
   [ "KC_NO", "KC_NO", "KC_NO", "KC_NO", "KC_NO" ],
   [ "KC_NO", "KC_NO", "KC_NO", "KC_NO", "KC_NO" ],
   [ "KC_NO", "KC_NO", "KC_NO", "KC_NO", "KC_NO" ],
   [ "KC_NO", "KC_NO", "KC_NO", "KC_NO", "KC_NO" ],
   [ "KC_NO", "KC_NO", "KC_NO", "KC_NO", "KC_NO" ],
   [ "KC_NO", "KC_NO", "KC_NO", "KC_NO", "KC_NO" ],
   [ "KC_NO", "KC_NO", "KC_NO", "KC_NO", "KC_NO" ],
   [ "KC_NO", "KC_NO", "KC_NO", "KC_NO", "KC_NO" ],
   [ "KC_NO", "KC_NO", "KC_NO", "KC_NO", "KC_NO" ],
   [ "KC_NO", "KC_NO", "KC_NO", "KC_NO", "KC_NO" ],
   [ "KC_NO", "KC_NO", "KC_NO", "KC_NO", "KC_NO" ],
   [ "KC_NO", "KC_NO", "KC_NO", "KC_NO", "KC_NO" ],
   [ "KC_NO", "KC_NO", "KC_NO", "KC_NO", "KC_NO" ],
   [ "KC_NO", "KC_NO", "KC_NO", "KC_NO", "KC_NO" ],
   [ "KC_NO", "KC_NO", "KC_NO", "KC_NO", "KC_NO" ],
   [ "KC_NO", "KC_NO", "KC_NO", "KC_NO", "KC_NO" ],
   [ "KC_NO", "KC_NO", "KC_NO", "KC_NO", "KC_NO" ],
   [ "KC_NO", "KC_NO", "KC_NO", "KC_NO", "KC_NO" ],
   [ "KC_NO", "KC_NO", "KC_NO", "KC_NO", "KC_NO" ],
   [ "KC_NO", "KC_NO", "KC_NO", "KC_NO", "KC_NO" ],
   [ "KC_NO", "KC_NO", "KC_NO", "KC_NO", "KC_NO" ],
   [ "KC_NO", "KC_NO", "KC_NO", "KC_NO", "KC_NO" ],
   [ "KC_NO", "KC_NO", "KC_NO", "KC_NO", "KC_NO" ],
   [ "KC_NO", "KC_NO", "KC_NO", "KC_NO", "KC_NO" ],
   [ "KC_NO", "KC_NO", "KC_NO", "KC_NO", "KC_NO" ],
   [ "KC_NO", "KC_NO", "KC_NO", "KC_NO", "KC_NO" ],
   [ "KC_NO", "KC_NO", "KC_NO", "KC_NO", "KC_NO" ],
   [ "KC_NO", "KC_NO", "KC_NO", "KC_NO", "KC_NO" ],
   [ "KC_NO", "KC_NO", "KC_NO", "KC_NO", "KC_NO" ],
   [ "KC_NO", "KC_NO", "KC_NO", "KC_NO", "KC_NO" ],
   [ "KC_NO", "KC_NO", "KC_NO", "KC_NO", "KC_NO" ],
 ],
   "custom_keycodes" : [
      {
         "shortName": "Left\nDPI +",
         "title": "Increase the DPI of the left pointing device.",
         "name": "SV_LEFT_DPI_INC"
      },
      {
         "shortName": "Left\nDPI -",
         "title": "Decrease the DPI of the left pointing device.",
         "name": "SV_LEFT_DPI_DEC"
      },
      {
         "shortName": "Right\nDPI +",
         "title": "Increase the DPI of the right pointing device.",
         "name": "SV_RIGHT_DPI_INC"
      },
      {
         "shortName": "Right\nDPI -",
         "title": "Decrease the DPI of the right pointing device.",
         "name": "SV_RIGHT_DPI_DEC"
      },
      {
         "shortName": "Scroll\nLeft\nToggle",
         "title": "Toggle if the left pointer is scroll or pointer.",
         "name": "SV_LEFT_SCROLL_TOGGLE"
      },
      {
         "shortName": "Scroll\nRight\nToggle",
         "title": "Toggle if the right pointer is scroll or pointer.",
         "name": "SV_RIGHT_SCROLL_TOGGLE"
      },
      {
         "shortName": "Fix\nDrift",
         "title": "Reset the calibration of the pointing device",
         "name": "SV_RECALIBRATE_POINTER"
      },
      {
         "shortName": "Mouse\nKey\nTimer",
         "title": "Cycle between various settings of the mouse keys timer.",
         "name": "SV_MH_CHANGE_TIMEOUTS"
      },
      {
         "shortName": "Caps\nWord\nToggle",
         "title": "Toggle Caps Word.",
         "name": "SV_CAPS_WORD"
      },
      {
         "shortName": "Toggle\nACH",
         "title": "Toggle Achordion",
         "name": "SV_TOGGLE_ACHORDION"
      },
      {
         "shortName": "MO 23\n(45=67)",
         "title": "Toggle layer 2 and 3, if 4 and 5 also active toggle 6 and 7",
         "name": "SV_TOGGLE_23_67"
      },
      {
         "shortName": "MO 45\n(23=67)",
         "title": "Toggle layer 4 and 5, if 2 and 3 also active toggle 6 and 7",
         "name": "SV_TOGGLE_45_67"
      },
      {
         "shortName": "Sniper\n2x",
         "title": "Slow the cursor 2x more.",
         "name": "SV_SNIPER_2"
      },
      {
         "shortName": "Sniper\n3x",
         "title": "Slow the cursor 3x more.",
         "name": "SV_SNIPER_3"
      },
      {
         "shortName": "Sniper\n5x",
         "title": "Slow the cursor 5x more.",
         "name": "SV_SNIPER_5"
      },
      {
         "shortName": "Scroll\nToggle\nHold",
         "title": "Hold to toggle the pointer's scroll status.",
         "name": "SV_SCROLL_HOLD"
      },
      {
         "shortName": "Scroll\nToggle",
         "title": "Toggle the pointer's scroll status.",
         "name": "SV_SCROLL_TOGGLE"
      },
      {
         "shortName": "Output\nStatus",
         "title": "Output the current internal state of the keyboard.",
         "name": "SV_OUTPUT_STATUS"
      }
   ],
 "extra" : {},
 "kbid" : "5199957870438586395",
 "key_override_count" : 30,
 "key_overrides" : [
    {
       "koid" : 0,
       "layers" : 65535,
       "negative_mod_mask" : 0,
       "options" : 7,
       "replacement" : "KC_NO",
       "suppressed_mods" : 0,
       "trigger" : "KC_NO",
       "trigger_mods" : 0
    },
    {
       "koid" : 1,
       "layers" : 65535,
       "negative_mod_mask" : 0,
       "options" : 7,
       "replacement" : "KC_NO",
       "suppressed_mods" : 0,
       "trigger" : "KC_NO",
       "trigger_mods" : 0
    },
    {
       "koid" : 2,
       "layers" : 65535,
       "negative_mod_mask" : 0,
       "options" : 7,
       "replacement" : "KC_NO",
       "suppressed_mods" : 0,
       "trigger" : "KC_NO",
       "trigger_mods" : 0
    },
    {
       "koid" : 3,
       "layers" : 65535,
       "negative_mod_mask" : 0,
       "options" : 7,
       "replacement" : "KC_NO",
       "suppressed_mods" : 0,
       "trigger" : "KC_NO",
       "trigger_mods" : 0
    },
    {
       "koid" : 4,
       "layers" : 65535,
       "negative_mod_mask" : 0,
       "options" : 7,
       "replacement" : "KC_NO",
       "suppressed_mods" : 0,
       "trigger" : "KC_NO",
       "trigger_mods" : 0
    },
    {
       "koid" : 5,
       "layers" : 65535,
       "negative_mod_mask" : 0,
       "options" : 7,
       "replacement" : "KC_NO",
       "suppressed_mods" : 0,
       "trigger" : "KC_NO",
       "trigger_mods" : 0
    },
    {
       "koid" : 6,
       "layers" : 65535,
       "negative_mod_mask" : 0,
       "options" : 7,
       "replacement" : "KC_NO",
       "suppressed_mods" : 0,
       "trigger" : "KC_NO",
       "trigger_mods" : 0
    },
    {
       "koid" : 7,
       "layers" : 65535,
       "negative_mod_mask" : 0,
       "options" : 7,
       "replacement" : "KC_NO",
       "suppressed_mods" : 0,
       "trigger" : "KC_NO",
       "trigger_mods" : 0
    },
    {
       "koid" : 8,
       "layers" : 65535,
       "negative_mod_mask" : 0,
       "options" : 7,
       "replacement" : "KC_NO",
       "suppressed_mods" : 0,
       "trigger" : "KC_NO",
       "trigger_mods" : 0
    },
    {
       "koid" : 9,
       "layers" : 65535,
       "negative_mod_mask" : 0,
       "options" : 7,
       "replacement" : "KC_NO",
       "suppressed_mods" : 0,
       "trigger" : "KC_NO",
       "trigger_mods" : 0
    },
    {
       "koid" : 10,
       "layers" : 65535,
       "negative_mod_mask" : 0,
       "options" : 7,
       "replacement" : "KC_NO",
       "suppressed_mods" : 0,
       "trigger" : "KC_NO",
       "trigger_mods" : 0
    },
    {
       "koid" : 11,
       "layers" : 65535,
       "negative_mod_mask" : 0,
       "options" : 7,
       "replacement" : "KC_NO",
       "suppressed_mods" : 0,
       "trigger" : "KC_NO",
       "trigger_mods" : 0
    },
    {
       "koid" : 12,
       "layers" : 65535,
       "negative_mod_mask" : 0,
       "options" : 7,
       "replacement" : "KC_NO",
       "suppressed_mods" : 0,
       "trigger" : "KC_NO",
       "trigger_mods" : 0
    },
    {
       "koid" : 13,
       "layers" : 65535,
       "negative_mod_mask" : 0,
       "options" : 7,
       "replacement" : "KC_NO",
       "suppressed_mods" : 0,
       "trigger" : "KC_NO",
       "trigger_mods" : 0
    },
    {
       "koid" : 14,
       "layers" : 65535,
       "negative_mod_mask" : 0,
       "options" : 7,
       "replacement" : "KC_NO",
       "suppressed_mods" : 0,
       "trigger" : "KC_NO",
       "trigger_mods" : 0
    },
    {
       "koid" : 15,
       "layers" : 65535,
       "negative_mod_mask" : 0,
       "options" : 7,
       "replacement" : "KC_NO",
       "suppressed_mods" : 0,
       "trigger" : "KC_NO",
       "trigger_mods" : 0
    },
    {
       "koid" : 16,
       "layers" : 65535,
       "negative_mod_mask" : 0,
       "options" : 7,
       "replacement" : "KC_NO",
       "suppressed_mods" : 0,
       "trigger" : "KC_NO",
       "trigger_mods" : 0
    },
    {
       "koid" : 17,
       "layers" : 65535,
       "negative_mod_mask" : 0,
       "options" : 7,
       "replacement" : "KC_NO",
       "suppressed_mods" : 0,
       "trigger" : "KC_NO",
       "trigger_mods" : 0
    },
    {
       "koid" : 18,
       "layers" : 65535,
       "negative_mod_mask" : 0,
       "options" : 7,
       "replacement" : "KC_NO",
       "suppressed_mods" : 0,
       "trigger" : "KC_NO",
       "trigger_mods" : 0
    },
    {
       "koid" : 19,
       "layers" : 65535,
       "negative_mod_mask" : 0,
       "options" : 7,
       "replacement" : "KC_NO",
       "suppressed_mods" : 0,
       "trigger" : "KC_NO",
       "trigger_mods" : 0
    },
    {
       "koid" : 20,
       "layers" : 65535,
       "negative_mod_mask" : 0,
       "options" : 7,
       "replacement" : "KC_NO",
       "suppressed_mods" : 0,
       "trigger" : "KC_NO",
       "trigger_mods" : 0
    },
    {
       "koid" : 21,
       "layers" : 65535,
       "negative_mod_mask" : 0,
       "options" : 7,
       "replacement" : "KC_NO",
       "suppressed_mods" : 0,
       "trigger" : "KC_NO",
       "trigger_mods" : 0
    },
    {
       "koid" : 22,
       "layers" : 65535,
       "negative_mod_mask" : 0,
       "options" : 7,
       "replacement" : "KC_NO",
       "suppressed_mods" : 0,
       "trigger" : "KC_NO",
       "trigger_mods" : 0
    },
    {
       "koid" : 23,
       "layers" : 65535,
       "negative_mod_mask" : 0,
       "options" : 7,
       "replacement" : "KC_NO",
       "suppressed_mods" : 0,
       "trigger" : "KC_NO",
       "trigger_mods" : 0
    },
    {
       "koid" : 24,
       "layers" : 65535,
       "negative_mod_mask" : 0,
       "options" : 7,
       "replacement" : "KC_NO",
       "suppressed_mods" : 0,
       "trigger" : "KC_NO",
       "trigger_mods" : 0
    },
    {
       "koid" : 25,
       "layers" : 65535,
       "negative_mod_mask" : 0,
       "options" : 7,
       "replacement" : "KC_NO",
       "suppressed_mods" : 0,
       "trigger" : "KC_NO",
       "trigger_mods" : 0
    },
    {
       "koid" : 26,
       "layers" : 65535,
       "negative_mod_mask" : 0,
       "options" : 7,
       "replacement" : "KC_NO",
       "suppressed_mods" : 0,
       "trigger" : "KC_NO",
       "trigger_mods" : 0
    },
    {
       "koid" : 27,
       "layers" : 65535,
       "negative_mod_mask" : 0,
       "options" : 7,
       "replacement" : "KC_NO",
       "suppressed_mods" : 0,
       "trigger" : "KC_NO",
       "trigger_mods" : 0
    },
    {
       "koid" : 28,
       "layers" : 65535,
       "negative_mod_mask" : 0,
       "options" : 7,
       "replacement" : "KC_NO",
       "suppressed_mods" : 0,
       "trigger" : "KC_NO",
       "trigger_mods" : 0
    },
    {
       "koid" : 29,
       "layers" : 65535,
       "negative_mod_mask" : 0,
       "options" : 7,
       "replacement" : "KC_NO",
       "suppressed_mods" : 0,
       "trigger" : "KC_NO",
       "trigger_mods" : 0
    }
 ],
 "keylayout" : {
    "0" : {
       "col" : 0,
       "color" : "#cccccc",
       "decal" : false,
       "ghost" : false,
       "h" : 1,
       "height2" : 1,
       "labels" : [],
       "nub" : false,
       "profile" : "",
       "rotation_angle" : 0,
       "rotation_x" : 0,
       "rotation_y" : 0,
       "row" : 0,
       "sb" : "",
       "sm" : "",
       "st" : "",
       "stepped" : false,
       "text" : "KC_LCTRL",
       "textColor" : "",
       "textSize" : [],
       "w" : 1.5,
       "width2" : 1,
       "x" : 10.6,
       "x2" : 0,
       "y" : 6,
       "y2" : 0
    },
    "1" : {
       "col" : 1,
       "color" : "#cccccc",
       "decal" : false,
       "ghost" : false,
       "h" : 1,
       "height2" : 1,
       "labels" : [],
       "nub" : false,
       "profile" : "",
       "rotation_angle" : 0,
       "rotation_x" : 0,
       "rotation_y" : 0,
       "row" : 0,
       "sb" : "",
       "sm" : "",
       "st" : "",
       "stepped" : false,
       "text" : "KC_TAB",
       "textColor" : "",
       "textSize" : [],
       "w" : 1.5,
       "width2" : 1,
       "x" : 10.6,
       "x2" : 0,
       "y" : 5,
       "y2" : 0
    },
    "10" : {
       "col" : 4,
       "color" : "#cccccc",
       "decal" : false,
       "ghost" : false,
       "h" : 1,
       "height2" : 1,
       "labels" : [],
       "nub" : false,
       "profile" : "",
       "rotation_angle" : 0,
       "rotation_x" : 0,
       "rotation_y" : 0,
       "row" : 1,
       "sb" : "",
       "sm" : "",
       "st" : "",
       "stepped" : false,
       "text" : "LSFT(KC_QUOTE)",
       "textColor" : "",
       "textSize" : [],
       "w" : 1,
       "width2" : 1,
       "x" : 8.5,
       "x2" : 0,
       "y" : 2.5,
       "y2" : 0
    },
    "12" : {
       "col" : 0,
       "color" : "#cccccc",
       "decal" : false,
       "ghost" : false,
       "h" : 1,
       "height2" : 1,
       "labels" : [],
       "nub" : false,
       "profile" : "",
       "rotation_angle" : 0,
       "rotation_x" : 0,
       "rotation_y" : 0,
       "row" : 2,
       "sb" : "",
       "sm" : "",
       "st" : "",
       "stepped" : false,
       "text" : "KC_C",
       "textColor" : "",
       "textSize" : [],
       "w" : 1,
       "width2" : 1,
       "x" : 7,
       "x2" : 0,
       "y" : 2,
       "y2" : 0
    },
    "13" : {
       "col" : 1,
       "color" : "#cccccc",
       "decal" : false,
       "ghost" : false,
       "h" : 1,
       "height2" : 1,
       "labels" : [],
       "nub" : false,
       "profile" : "",
       "rotation_angle" : 0,
       "rotation_x" : 0,
       "rotation_y" : 0,
       "row" : 2,
       "sb" : "",
       "sm" : "",
       "st" : "",
       "stepped" : false,
       "text" : "KC_T",
       "textColor" : "",
       "textSize" : [],
       "w" : 1,
       "width2" : 1,
       "x" : 8,
       "x2" : 0,
       "y" : 1,
       "y2" : 0
    },
    "14" : {
       "col" : 2,
       "color" : "#cccccc",
       "decal" : false,
       "ghost" : false,
       "h" : 1,
       "height2" : 1,
       "labels" : [],
       "nub" : false,
       "profile" : "",
       "rotation_angle" : 0,
       "rotation_x" : 0,
       "rotation_y" : 0,
       "row" : 2,
       "sb" : "",
       "sm" : "",
       "st" : "",
       "stepped" : false,
       "text" : "KC_D",
       "textColor" : "",
       "textSize" : [],
       "w" : 1,
       "width2" : 1,
       "x" : 7,
       "x2" : 0,
       "y" : 1,
       "y2" : 0
    },
    "15" : {
       "col" : 3,
       "color" : "#cccccc",
       "decal" : false,
       "ghost" : false,
       "h" : 1,
       "height2" : 1,
       "labels" : [],
       "nub" : false,
       "profile" : "",
       "rotation_angle" : 0,
       "rotation_x" : 0,
       "rotation_y" : 0,
       "row" : 2,
       "sb" : "",
       "sm" : "",
       "st" : "",
       "stepped" : false,
       "text" : "KC_E",
       "textColor" : "",
       "textSize" : [],
       "w" : 1,
       "width2" : 1,
       "x" : 7,
       "x2" : 0,
       "y" : 0,
       "y2" : 0
    },
    "16" : {
       "col" : 4,
       "color" : "#cccccc",
       "decal" : false,
       "ghost" : false,
       "h" : 1,
       "height2" : 1,
       "labels" : [],
       "nub" : false,
       "profile" : "",
       "rotation_angle" : 0,
       "rotation_x" : 0,
       "rotation_y" : 0,
       "row" : 2,
       "sb" : "",
       "sm" : "",
       "st" : "",
       "stepped" : false,
       "text" : "KC_GRAVE",
       "textColor" : "",
       "textSize" : [],
       "w" : 1,
       "width2" : 1,
       "x" : 6,
       "x2" : 0,
       "y" : 1,
       "y2" : 0
    },
    "18" : {
       "col" : 0,
       "color" : "#cccccc",
       "decal" : false,
       "ghost" : false,
       "h" : 1,
       "height2" : 1,
       "labels" : [],
       "nub" : false,
       "profile" : "",
       "rotation_angle" : 0,
       "rotation_x" : 0,
       "rotation_y" : 0,
       "row" : 3,
       "sb" : "",
       "sm" : "",
       "st" : "",
       "stepped" : false,
       "text" : "KC_X",
       "textColor" : "",
       "textSize" : [],
       "w" : 1,
       "width2" : 1,
       "x" : 3.5,
       "x2" : 0,
       "y" : 2,
       "y2" : 0
    },
    "19" : {
       "col" : 1,
       "color" : "#cccccc",
       "decal" : false,
       "ghost" : false,
       "h" : 1,
       "height2" : 1,
       "labels" : [],
       "nub" : false,
       "profile" : "",
       "rotation_angle" : 0,
       "rotation_x" : 0,
       "rotation_y" : 0,
       "row" : 3,
       "sb" : "",
       "sm" : "",
       "st" : "",
       "stepped" : false,
       "text" : "KC_B",
       "textColor" : "",
       "textSize" : [],
       "w" : 1,
       "width2" : 1,
       "x" : 4.5,
       "x2" : 0,
       "y" : 1,
       "y2" : 0
    },
    "2" : {
       "col" : 2,
       "color" : "#cccccc",
       "decal" : false,
       "ghost" : false,
       "h" : 1,
       "height2" : 1,
       "labels" : [],
       "nub" : false,
       "profile" : "",
       "rotation_angle" : 0,
       "rotation_x" : 0,
       "rotation_y" : 0,
       "row" : 0,
       "sb" : "",
       "sm" : "",
       "st" : "",
       "stepped" : false,
       "text" : "KC_LSHIFT",
       "textColor" : "",
       "textSize" : [],
       "w" : 1,
       "width2" : 1,
       "x" : 9.5,
       "x2" : 0,
       "y" : 6,
       "y2" : 0
    },
    "20" : {
       "col" : 2,
       "color" : "#cccccc",
       "decal" : false,
       "ghost" : false,
       "h" : 1,
       "height2" : 1,
       "labels" : [],
       "nub" : false,
       "profile" : "",
       "rotation_angle" : 0,
       "rotation_x" : 0,
       "rotation_y" : 0,
       "row" : 3,
       "sb" : "",
       "sm" : "",
       "st" : "",
       "stepped" : false,
       "text" : "KC_S",
       "textColor" : "",
       "textSize" : [],
       "w" : 1,
       "width2" : 1,
       "x" : 3.5,
       "x2" : 0,
       "y" : 1,
       "y2" : 0
    },
    "21" : {
       "col" : 3,
       "color" : "#cccccc",
       "decal" : false,
       "ghost" : false,
       "h" : 1,
       "height2" : 1,
       "labels" : [],
       "nub" : false,
       "profile" : "",
       "rotation_angle" : 0,
       "rotation_x" : 0,
       "rotation_y" : 0,
       "row" : 3,
       "sb" : "",
       "sm" : "",
       "st" : "",
       "stepped" : false,
       "text" : "KC_W",
       "textColor" : "",
       "textSize" : [],
       "w" : 1,
       "width2" : 1,
       "x" : 3.5,
       "x2" : 0,
       "y" : 0,
       "y2" : 0
    },
    "22" : {
       "col" : 4,
       "color" : "#cccccc",
       "decal" : false,
       "ghost" : false,
       "h" : 1,
       "height2" : 1,
       "labels" : [],
       "nub" : false,
       "profile" : "",
       "rotation_angle" : 0,
       "rotation_x" : 0,
       "rotation_y" : 0,
       "row" : 3,
       "sb" : "",
       "sm" : "",
       "st" : "",
       "stepped" : false,
       "text" : "KC_ESCAPE",
       "textColor" : "",
       "textSize" : [],
       "w" : 1,
       "width2" : 1,
       "x" : 2.5,
       "x2" : 0,
       "y" : 1,
       "y2" : 0
    },
    "24" : {
       "col" : 0,
       "color" : "#cccccc",
       "decal" : false,
       "ghost" : false,
       "h" : 1,
       "height2" : 1,
       "labels" : [],
       "nub" : false,
       "profile" : "",
       "rotation_angle" : 0,
       "rotation_x" : 0,
       "rotation_y" : 0,
       "row" : 4,
       "sb" : "",
       "sm" : "",
       "st" : "",
       "stepped" : false,
       "text" : "KC_Z",
       "textColor" : "",
       "textSize" : [],
       "w" : 1,
       "width2" : 1,
       "x" : 1,
       "x2" : 0,
       "y" : 3.5,
       "y2" : 0
    },
    "25" : {
       "col" : 1,
       "color" : "#cccccc",
       "decal" : false,
       "ghost" : false,
       "h" : 1,
       "height2" : 1,
       "labels" : [],
       "nub" : false,
       "profile" : "",
       "rotation_angle" : 0,
       "rotation_x" : 0,
       "rotation_y" : 0,
       "row" : 4,
       "sb" : "",
       "sm" : "",
       "st" : "",
       "stepped" : false,
       "text" : "KC_LBRACKET",
       "textColor" : "",
       "textSize" : [],
       "w" : 1,
       "width2" : 1,
       "x" : 2,
       "x2" : 0,
       "y" : 2.5,
       "y2" : 0
    },
    "26" : {
       "col" : 2,
       "color" : "#cccccc",
       "decal" : false,
       "ghost" : false,
       "h" : 1,
       "height2" : 1,
       "labels" : [],
       "nub" : false,
       "profile" : "",
       "rotation_angle" : 0,
       "rotation_x" : 0,
       "rotation_y" : 0,
       "row" : 4,
       "sb" : "",
       "sm" : "",
       "st" : "",
       "stepped" : false,
       "text" : "KC_A",
       "textColor" : "",
       "textSize" : [],
       "w" : 1,
       "width2" : 1,
       "x" : 1,
       "x2" : 0,
       "y" : 2.5,
       "y2" : 0
    },
    "27" : {
       "col" : 3,
       "color" : "#cccccc",
       "decal" : false,
       "ghost" : false,
       "h" : 1,
       "height2" : 1,
       "labels" : [],
       "nub" : false,
       "profile" : "",
       "rotation_angle" : 0,
       "rotation_x" : 0,
       "rotation_y" : 0,
       "row" : 4,
       "sb" : "",
       "sm" : "",
       "st" : "",
       "stepped" : false,
       "text" : "KC_Q",
       "textColor" : "",
       "textSize" : [],
       "w" : 1,
       "width2" : 1,
       "x" : 1,
       "x2" : 0,
       "y" : 1.5,
       "y2" : 0
    },
    "28" : {
       "col" : 4,
       "color" : "#cccccc",
       "decal" : false,
       "ghost" : false,
       "h" : 1,
       "height2" : 1,
       "labels" : [],
       "nub" : false,
       "profile" : "",
       "rotation_angle" : 0,
       "rotation_x" : 0,
       "rotation_y" : 0,
       "row" : 4,
       "sb" : "",
       "sm" : "",
       "st" : "",
       "stepped" : false,
       "text" : "KC_DELETE",
       "textColor" : "",
       "textSize" : [],
       "w" : 1,
       "width2" : 1,
       "x" : 0,
       "x2" : 0,
       "y" : 2.5,
       "y2" : 0
    },
    "3" : {
       "col" : 3,
       "color" : "#cccccc",
       "decal" : false,
       "ghost" : false,
       "h" : 1,
       "height2" : 1,
       "labels" : [],
       "nub" : false,
       "profile" : "",
       "rotation_angle" : 0,
       "rotation_x" : 0,
       "rotation_y" : 0,
       "row" : 0,
       "sb" : "",
       "sm" : "",
       "st" : "",
       "stepped" : false,
       "text" : "KC_ENTER",
       "textColor" : "",
       "textSize" : [],
       "w" : 1.5,
       "width2" : 1,
       "x" : 7.9,
       "x2" : 0,
       "y" : 5,
       "y2" : 0
    },
    "30" : {
       "col" : 0,
       "color" : "#cccccc",
       "decal" : false,
       "ghost" : false,
       "h" : 1,
       "height2" : 1,
       "labels" : [],
       "nub" : false,
       "profile" : "",
       "rotation_angle" : 0,
       "rotation_x" : 0,
       "rotation_y" : 0,
       "row" : 5,
       "sb" : "",
       "sm" : "",
       "st" : "",
       "stepped" : false,
       "text" : "KC_LALT",
       "textColor" : "",
       "textSize" : [],
       "w" : 1.5,
       "width2" : 1,
       "x" : 12.9,
       "x2" : 0,
       "y" : 6,
       "y2" : 0
    },
    "31" : {
       "col" : 1,
       "color" : "#cccccc",
       "decal" : false,
       "ghost" : false,
       "h" : 1,
       "height2" : 1,
       "labels" : [],
       "nub" : false,
       "profile" : "",
       "rotation_angle" : 0,
       "rotation_x" : 0,
       "rotation_y" : 0,
       "row" : 5,
       "sb" : "",
       "sm" : "",
       "st" : "",
       "stepped" : false,
       "text" : "KC_BSPACE",
       "textColor" : "",
       "textSize" : [],
       "w" : 1.5,
       "width2" : 1,
       "x" : 12.9,
       "x2" : 0,
       "y" : 5,
       "y2" : 0
    },
    "32" : {
       "col" : 2,
       "color" : "#cccccc",
       "decal" : false,
       "ghost" : false,
       "h" : 1,
       "height2" : 1,
       "labels" : [],
       "nub" : false,
       "profile" : "",
       "rotation_angle" : 0,
       "rotation_x" : 0,
       "rotation_y" : 0,
       "row" : 5,
       "sb" : "",
       "sm" : "",
       "st" : "",
       "stepped" : false,
       "text" : "MO(4)",
       "textColor" : "",
       "textSize" : [],
       "w" : 1,
       "width2" : 1,
       "x" : 14.5,
       "x2" : 0,
       "y" : 6,
       "y2" : 0
    },
    "33" : {
       "col" : 3,
       "color" : "#cccccc",
       "decal" : false,
       "ghost" : false,
       "h" : 1,
       "height2" : 1,
       "labels" : [],
       "nub" : false,
       "profile" : "",
       "rotation_angle" : 0,
       "rotation_x" : 0,
       "rotation_y" : 0,
       "row" : 5,
       "sb" : "",
       "sm" : "",
       "st" : "",
       "stepped" : false,
       "text" : "KC_SPACE",
       "textColor" : "",
       "textSize" : [],
       "w" : 1.5,
       "width2" : 1,
       "x" : 15.6,
       "x2" : 0,
       "y" : 5,
       "y2" : 0
    },
    "34" : {
       "col" : 4,
       "color" : "#cccccc",
       "decal" : false,
       "ghost" : false,
       "h" : 1,
       "height2" : 1,
       "labels" : [],
       "nub" : false,
       "profile" : "",
       "rotation_angle" : 0,
       "rotation_x" : 0,
       "rotation_y" : 0,
       "row" : 5,
       "sb" : "",
       "sm" : "",
       "st" : "",
       "stepped" : false,
       "text" : "MO(2)",
       "textColor" : "",
       "textSize" : [],
       "w" : 2,
       "width2" : 1,
       "x" : 15.6,
       "x2" : 0,
       "y" : 6,
       "y2" : 0
    },
    "35" : {
       "col" : 5,
       "color" : "#cccccc",
       "decal" : false,
       "ghost" : false,
       "h" : 1,
       "height2" : 1,
       "labels" : [],
       "nub" : false,
       "profile" : "",
       "rotation_angle" : 0,
       "rotation_x" : 0,
       "rotation_y" : 0,
       "row" : 5,
       "sb" : "",
       "sm" : "",
       "st" : "",
       "stepped" : false,
       "text" : "MO(5)",
       "textColor" : "",
       "textSize" : [],
       "w" : 1,
       "width2" : 1,
       "x" : 14.5,
       "x2" : 0,
       "y" : 5,
       "y2" : 0
    },
    "36" : {
       "col" : 0,
       "color" : "#cccccc",
       "decal" : false,
       "ghost" : false,
       "h" : 1,
       "height2" : 1,
       "labels" : [],
       "nub" : false,
       "profile" : "",
       "rotation_angle" : 0,
       "rotation_x" : 0,
       "rotation_y" : 0,
       "row" : 6,
       "sb" : "",
       "sm" : "",
       "st" : "",
       "stepped" : false,
       "text" : "KC_M",
       "textColor" : "",
       "textSize" : [],
       "w" : 1,
       "width2" : 1,
       "x" : 14.5,
       "x2" : 0,
       "y" : 3.5,
       "y2" : 0
    },
    "37" : {
       "col" : 1,
       "color" : "#cccccc",
       "decal" : false,
       "ghost" : false,
       "h" : 1,
       "height2" : 1,
       "labels" : [],
       "nub" : false,
       "profile" : "",
       "rotation_angle" : 0,
       "rotation_x" : 0,
       "rotation_y" : 0,
       "row" : 6,
       "sb" : "",
       "sm" : "",
       "st" : "",
       "stepped" : false,
       "text" : "KC_QUOTE",
       "textColor" : "",
       "textSize" : [],
       "w" : 1,
       "width2" : 1,
       "x" : 15.5,
       "x2" : 0,
       "y" : 2.5,
       "y2" : 0
    },
    "38" : {
       "col" : 2,
       "color" : "#cccccc",
       "decal" : false,
       "ghost" : false,
       "h" : 1,
       "height2" : 1,
       "labels" : [],
       "nub" : false,
       "profile" : "",
       "rotation_angle" : 0,
       "rotation_x" : 0,
       "rotation_y" : 0,
       "row" : 6,
       "sb" : "",
       "sm" : "",
       "st" : "",
       "stepped" : false,
       "text" : "KC_J",
       "textColor" : "",
       "textSize" : [],
       "w" : 1,
       "width2" : 1,
       "x" : 14.5,
       "x2" : 0,
       "y" : 2.5,
       "y2" : 0
    },
    "39" : {
       "col" : 3,
       "color" : "#cccccc",
       "decal" : false,
       "ghost" : false,
       "h" : 1,
       "height2" : 1,
       "labels" : [],
       "nub" : false,
       "profile" : "",
       "rotation_angle" : 0,
       "rotation_x" : 0,
       "rotation_y" : 0,
       "row" : 6,
       "sb" : "",
       "sm" : "",
       "st" : "",
       "stepped" : false,
       "text" : "KC_U",
       "textColor" : "",
       "textSize" : [],
       "w" : 1,
       "width2" : 1,
       "x" : 14.5,
       "x2" : 0,
       "y" : 1.5,
       "y2" : 0
    },
    "4" : {
       "col" : 4,
       "color" : "#cccccc",
       "decal" : false,
       "ghost" : false,
       "h" : 1,
       "height2" : 1,
       "labels" : [],
       "nub" : false,
       "profile" : "",
       "rotation_angle" : 0,
       "rotation_x" : 0,
       "rotation_y" : 0,
       "row" : 0,
       "sb" : "",
       "sm" : "",
       "st" : "",
       "stepped" : false,
       "text" : "MO(14)",
       "textColor" : "",
       "textSize" : [],
       "w" : 2,
       "width2" : 1,
       "x" : 7.4,
       "x2" : 0,
       "y" : 6,
       "y2" : 0
    },
    "40" : {
       "col" : 4,
       "color" : "#cccccc",
       "decal" : false,
       "ghost" : false,
       "h" : 1,
       "height2" : 1,
       "labels" : [],
       "nub" : false,
       "profile" : "",
       "rotation_angle" : 0,
       "rotation_x" : 0,
       "rotation_y" : 0,
       "row" : 6,
       "sb" : "",
       "sm" : "",
       "st" : "",
       "stepped" : false,
       "text" : "KC_H",
       "textColor" : "",
       "textSize" : [],
       "w" : 1,
       "width2" : 1,
       "x" : 13.5,
       "x2" : 0,
       "y" : 2.5,
       "y2" : 0
    },
    "42" : {
       "col" : 0,
       "color" : "#cccccc",
       "decal" : false,
       "ghost" : false,
       "h" : 1,
       "height2" : 1,
       "labels" : [],
       "nub" : false,
       "profile" : "",
       "rotation_angle" : 0,
       "rotation_x" : 0,
       "rotation_y" : 0,
       "row" : 7,
       "sb" : "",
       "sm" : "",
       "st" : "",
       "stepped" : false,
       "text" : "KC_COMMA",
       "textColor" : "",
       "textSize" : [],
       "w" : 1,
       "width2" : 1,
       "x" : 17,
       "x2" : 0,
       "y" : 2,
       "y2" : 0
    },
    "43" : {
       "col" : 1,
       "color" : "#cccccc",
       "decal" : false,
       "ghost" : false,
       "h" : 1,
       "height2" : 1,
       "labels" : [],
       "nub" : false,
       "profile" : "",
       "rotation_angle" : 0,
       "rotation_x" : 0,
       "rotation_y" : 0,
       "row" : 7,
       "sb" : "",
       "sm" : "",
       "st" : "",
       "stepped" : false,
       "text" : "LSFT(KC_SCOLON)",
       "textColor" : "",
       "textSize" : [],
       "w" : 1,
       "width2" : 1,
       "x" : 18,
       "x2" : 0,
       "y" : 1,
       "y2" : 0
    },
    "44" : {
       "col" : 2,
       "color" : "#cccccc",
       "decal" : false,
       "ghost" : false,
       "h" : 1,
       "height2" : 1,
       "labels" : [],
       "nub" : false,
       "profile" : "",
       "rotation_angle" : 0,
       "rotation_x" : 0,
       "rotation_y" : 0,
       "row" : 7,
       "sb" : "",
       "sm" : "",
       "st" : "",
       "stepped" : false,
       "text" : "KC_K",
       "textColor" : "",
       "textSize" : [],
       "w" : 1,
       "width2" : 1,
       "x" : 17,
       "x2" : 0,
       "y" : 1,
       "y2" : 0
    },
    "45" : {
       "col" : 3,
       "color" : "#cccccc",
       "decal" : false,
       "ghost" : false,
       "h" : 1,
       "height2" : 1,
       "labels" : [],
       "nub" : false,
       "profile" : "",
       "rotation_angle" : 0,
       "rotation_x" : 0,
       "rotation_y" : 0,
       "row" : 7,
       "sb" : "",
       "sm" : "",
       "st" : "",
       "stepped" : false,
       "text" : "KC_I",
       "textColor" : "",
       "textSize" : [],
       "w" : 1,
       "width2" : 1,
       "x" : 17,
       "x2" : 0,
       "y" : 0,
       "y2" : 0
    },
    "46" : {
       "col" : 4,
       "color" : "#cccccc",
       "decal" : false,
       "ghost" : false,
       "h" : 1,
       "height2" : 1,
       "labels" : [],
       "nub" : false,
       "profile" : "",
       "rotation_angle" : 0,
       "rotation_x" : 0,
       "rotation_y" : 0,
       "row" : 7,
       "sb" : "",
       "sm" : "",
       "st" : "",
       "stepped" : false,
       "text" : "KC_Y",
       "textColor" : "",
       "textSize" : [],
       "w" : 1,
       "width2" : 1,
       "x" : 16,
       "x2" : 0,
       "y" : 1,
       "y2" : 0
    },
    "48" : {
       "col" : 0,
       "color" : "#cccccc",
       "decal" : false,
       "ghost" : false,
       "h" : 1,
       "height2" : 1,
       "labels" : [],
       "nub" : false,
       "profile" : "",
       "rotation_angle" : 0,
       "rotation_x" : 0,
       "rotation_y" : 0,
       "row" : 8,
       "sb" : "",
       "sm" : "",
       "st" : "",
       "stepped" : false,
       "text" : "KC_DOT",
       "textColor" : "",
       "textSize" : [],
       "w" : 1,
       "width2" : 1,
       "x" : 20.5,
       "x2" : 0,
       "y" : 2,
       "y2" : 0
    },
    "49" : {
       "col" : 1,
       "color" : "#cccccc",
       "decal" : false,
       "ghost" : false,
       "h" : 1,
       "height2" : 1,
       "labels" : [],
       "nub" : false,
       "profile" : "",
       "rotation_angle" : 0,
       "rotation_x" : 0,
       "rotation_y" : 0,
       "row" : 8,
       "sb" : "",
       "sm" : "",
       "st" : "",
       "stepped" : false,
       "text" : "KC_NO",
       "textColor" : "",
       "textSize" : [],
       "w" : 1,
       "width2" : 1,
       "x" : 21.5,
       "x2" : 0,
       "y" : 1,
       "y2" : 0
    },
    "5" : {
       "col" : 5,
       "color" : "#cccccc",
       "decal" : false,
       "ghost" : false,
       "h" : 1,
       "height2" : 1,
       "labels" : [],
       "nub" : false,
       "profile" : "",
       "rotation_angle" : 0,
       "rotation_x" : 0,
       "rotation_y" : 0,
       "row" : 0,
       "sb" : "",
       "sm" : "",
       "st" : "",
       "stepped" : false,
       "text" : "KC_CAPSLOCK",
       "textColor" : "",
       "textSize" : [],
       "w" : 1,
       "width2" : 1,
       "x" : 9.5,
       "x2" : 0,
       "y" : 5,
       "y2" : 0
    },
    "50" : {
       "col" : 2,
       "color" : "#cccccc",
       "decal" : false,
       "ghost" : false,
       "h" : 1,
       "height2" : 1,
       "labels" : [],
       "nub" : false,
       "profile" : "",
       "rotation_angle" : 0,
       "rotation_x" : 0,
       "rotation_y" : 0,
       "row" : 8,
       "sb" : "",
       "sm" : "",
       "st" : "",
       "stepped" : false,
       "text" : "KC_L",
       "textColor" : "",
       "textSize" : [],
       "w" : 1,
       "width2" : 1,
       "x" : 20.5,
       "x2" : 0,
       "y" : 1,
       "y2" : 0
    },
    "51" : {
       "col" : 3,
       "color" : "#cccccc",
       "decal" : false,
       "ghost" : false,
       "h" : 1,
       "height2" : 1,
       "labels" : [],
       "nub" : false,
       "profile" : "",
       "rotation_angle" : 0,
       "rotation_x" : 0,
       "rotation_y" : 0,
       "row" : 8,
       "sb" : "",
       "sm" : "",
       "st" : "",
       "stepped" : false,
       "text" : "KC_O",
       "textColor" : "",
       "textSize" : [],
       "w" : 1,
       "width2" : 1,
       "x" : 20.5,
       "x2" : 0,
       "y" : 0,
       "y2" : 0
    },
    "52" : {
       "col" : 4,
       "color" : "#cccccc",
       "decal" : false,
       "ghost" : false,
       "h" : 1,
       "height2" : 1,
       "labels" : [],
       "nub" : false,
       "profile" : "",
       "rotation_angle" : 0,
       "rotation_x" : 0,
       "rotation_y" : 0,
       "row" : 8,
       "sb" : "",
       "sm" : "",
       "st" : "",
       "stepped" : false,
       "text" : "KC_N",
       "textColor" : "",
       "textSize" : [],
       "w" : 1,
       "width2" : 1,
       "x" : 19.5,
       "x2" : 0,
       "y" : 1,
       "y2" : 0
    },
    "54" : {
       "col" : 0,
       "color" : "#cccccc",
       "decal" : false,
       "ghost" : false,
       "h" : 1,
       "height2" : 1,
       "labels" : [],
       "nub" : false,
       "profile" : "",
       "rotation_angle" : 0,
       "rotation_x" : 0,
       "rotation_y" : 0,
       "row" : 9,
       "sb" : "",
       "sm" : "",
       "st" : "",
       "stepped" : false,
       "text" : "KC_SLASH",
       "textColor" : "",
       "textSize" : [],
       "w" : 1,
       "width2" : 1,
       "x" : 23,
       "x2" : 0,
       "y" : 3.5,
       "y2" : 0
    },
    "55" : {
       "col" : 1,
       "color" : "#cccccc",
       "decal" : false,
       "ghost" : false,
       "h" : 1,
       "height2" : 1,
       "labels" : [],
       "nub" : false,
       "profile" : "",
       "rotation_angle" : 0,
       "rotation_x" : 0,
       "rotation_y" : 0,
       "row" : 9,
       "sb" : "",
       "sm" : "",
       "st" : "",
       "stepped" : false,
       "text" : "KC_BSLASH",
       "textColor" : "",
       "textSize" : [],
       "w" : 1,
       "width2" : 1,
       "x" : 24,
       "x2" : 0,
       "y" : 2.5,
       "y2" : 0
    },
    "56" : {
       "col" : 2,
       "color" : "#cccccc",
       "decal" : false,
       "ghost" : false,
       "h" : 1,
       "height2" : 1,
       "labels" : [],
       "nub" : false,
       "profile" : "",
       "rotation_angle" : 0,
       "rotation_x" : 0,
       "rotation_y" : 0,
       "row" : 9,
       "sb" : "",
       "sm" : "",
       "st" : "",
       "stepped" : false,
       "text" : "KC_SCOLON",
       "textColor" : "",
       "textSize" : [],
       "w" : 1,
       "width2" : 1,
       "x" : 23,
       "x2" : 0,
       "y" : 2.5,
       "y2" : 0
    },
    "57" : {
       "col" : 3,
       "color" : "#cccccc",
       "decal" : false,
       "ghost" : false,
       "h" : 1,
       "height2" : 1,
       "labels" : [],
       "nub" : false,
       "profile" : "",
       "rotation_angle" : 0,
       "rotation_x" : 0,
       "rotation_y" : 0,
       "row" : 9,
       "sb" : "",
       "sm" : "",
       "st" : "",
       "stepped" : false,
       "text" : "KC_P",
       "textColor" : "",
       "textSize" : [],
       "w" : 1,
       "width2" : 1,
       "x" : 23,
       "x2" : 0,
       "y" : 1.5,
       "y2" : 0
    },
    "58" : {
       "col" : 4,
       "color" : "#cccccc",
       "decal" : false,
       "ghost" : false,
       "h" : 1,
       "height2" : 1,
       "labels" : [],
       "nub" : false,
       "profile" : "",
       "rotation_angle" : 0,
       "rotation_x" : 0,
       "rotation_y" : 0,
       "row" : 9,
       "sb" : "",
       "sm" : "",
       "st" : "",
       "stepped" : false,
       "text" : "KC_RBRACKET",
       "textColor" : "",
       "textSize" : [],
       "w" : 1,
       "width2" : 1,
       "x" : 22,
       "x2" : 0,
       "y" : 2.5,
       "y2" : 0
    },
    "6" : {
       "col" : 0,
       "color" : "#cccccc",
       "decal" : false,
       "ghost" : false,
       "h" : 1,
       "height2" : 1,
       "labels" : [],
       "nub" : false,
       "profile" : "",
       "rotation_angle" : 0,
       "rotation_x" : 0,
       "rotation_y" : 0,
       "row" : 1,
       "sb" : "",
       "sm" : "",
       "st" : "",
       "stepped" : false,
       "text" : "KC_V",
       "textColor" : "",
       "textSize" : [],
       "w" : 1,
       "width2" : 1,
       "x" : 9.5,
       "x2" : 0,
       "y" : 3.5,
       "y2" : 0
    },
    "7" : {
       "col" : 1,
       "color" : "#cccccc",
       "decal" : false,
       "ghost" : false,
       "h" : 1,
       "height2" : 1,
       "labels" : [],
       "nub" : false,
       "profile" : "",
       "rotation_angle" : 0,
       "rotation_x" : 0,
       "rotation_y" : 0,
       "row" : 1,
       "sb" : "",
       "sm" : "",
       "st" : "",
       "stepped" : false,
       "text" : "KC_G",
       "textColor" : "",
       "textSize" : [],
       "w" : 1,
       "width2" : 1,
       "x" : 10.5,
       "x2" : 0,
       "y" : 2.5,
       "y2" : 0
    },
    "8" : {
       "col" : 2,
       "color" : "#cccccc",
       "decal" : false,
       "ghost" : false,
       "h" : 1,
       "height2" : 1,
       "labels" : [],
       "nub" : false,
       "profile" : "",
       "rotation_angle" : 0,
       "rotation_x" : 0,
       "rotation_y" : 0,
       "row" : 1,
       "sb" : "",
       "sm" : "",
       "st" : "",
       "stepped" : false,
       "text" : "KC_F",
       "textColor" : "",
       "textSize" : [],
       "w" : 1,
       "width2" : 1,
       "x" : 9.5,
       "x2" : 0,
       "y" : 2.5,
       "y2" : 0
    },
    "9" : {
       "col" : 3,
       "color" : "#cccccc",
       "decal" : false,
       "ghost" : false,
       "h" : 1,
       "height2" : 1,
       "labels" : [],
       "nub" : false,
       "profile" : "",
       "rotation_angle" : 0,
       "rotation_x" : 0,
       "rotation_y" : 0,
       "row" : 1,
       "sb" : "",
       "sm" : "",
       "st" : "",
       "stepped" : false,
       "text" : "KC_R",
       "textColor" : "",
       "textSize" : [],
       "w" : 1,
       "width2" : 1,
       "x" : 9.5,
       "x2" : 0,
       "y" : 1.5,
       "y2" : 0
    }
 },
   "payload": {
      "name": "Svalboard Vial Definition",
      "author": "Morgan Venable",
      "notes": "This is a Vial Keymap template for Svalboard",
      "vendorId": "0x303A",
      "productId": "0x4044",
      "lighting": "none",
      "matrix": {
         "rows": 10,
         "cols": 6
      },
      "customKeycodes": [
         {
            "shortName": "Left\nDPI +",
            "title": "Increase the DPI of the left pointing device.",
            "name": "SV_LEFT_DPI_INC"
         },
         {
            "shortName": "Left\nDPI -",
            "title": "Decrease the DPI of the left pointing device.",
            "name": "SV_LEFT_DPI_DEC"
         },
         {
            "shortName": "Right\nDPI +",
            "title": "Increase the DPI of the right pointing device.",
            "name": "SV_RIGHT_DPI_INC"
         },
         {
            "shortName": "Right\nDPI -",
            "title": "Decrease the DPI of the right pointing device.",
            "name": "SV_RIGHT_DPI_DEC"
         },
         {
            "shortName": "Scroll\nLeft\nToggle",
            "title": "Toggle if the left pointer is scroll or pointer.",
            "name": "SV_LEFT_SCROLL_TOGGLE"
         },
         {
            "shortName": "Scroll\nRight\nToggle",
            "title": "Toggle if the right pointer is scroll or pointer.",
            "name": "SV_RIGHT_SCROLL_TOGGLE"
         },
         {
            "shortName": "Fix\nDrift",
            "title": "Reset the calibration of the pointing device",
            "name": "SV_RECALIBRATE_POINTER"
         },
         {
            "shortName": "Mouse\nKey\nTimer",
            "title": "Cycle between various settings of the mouse keys timer.",
            "name": "SV_MH_CHANGE_TIMEOUTS"
         },
         {
            "shortName": "Caps\nWord\nToggle",
            "title": "Toggle Caps Word.",
            "name": "SV_CAPS_WORD"
         },
         {
            "shortName": "Toggle\nACH",
            "title": "Toggle Achordion",
            "name": "SV_TOGGLE_ACHORDION"
         },
         {
            "shortName": "MO 23\n(45=67)",
            "title": "Toggle layer 2 and 3, if 4 and 5 also active toggle 6 and 7",
            "name": "SV_TOGGLE_23_67"
         },
         {
            "shortName": "MO 45\n(23=67)",
            "title": "Toggle layer 4 and 5, if 2 and 3 also active toggle 6 and 7",
            "name": "SV_TOGGLE_45_67"
         },
         {
            "shortName": "Sniper\n2x",
            "title": "Slow the cursor 2x more.",
            "name": "SV_SNIPER_2"
         },
         {
            "shortName": "Sniper\n3x",
            "title": "Slow the cursor 3x more.",
            "name": "SV_SNIPER_3"
         },
         {
            "shortName": "Sniper\n5x",
            "title": "Slow the cursor 5x more.",
            "name": "SV_SNIPER_5"
         },
         {
            "shortName": "Scroll\nToggle\nHold",
            "title": "Hold to toggle the pointer's scroll status.",
            "name": "SV_SCROLL_HOLD"
         },
         {
            "shortName": "Scroll\nToggle",
            "title": "Toggle the pointer's scroll status.",
            "name": "SV_SCROLL_TOGGLE"
         },
         {
            "shortName": "Output\nStatus",
            "title": "Output the current internal state of the keyboard.",
            "name": "SV_OUTPUT_STATUS"
         }
      ],
      "layouts": {
         "keymap": [
            [
               {
                  "x": 3.5
               },
               "3,3",
               {
                  "x": 2.5
               },
               "2,3",
               {
                  "x": 9
               },
               "7,3",
               {
                  "x": 2.5
               },
               "8,3"
            ],
            [
               {
                  "x": 2.5
               },
               "3,4",
               "3,2",
               "3,1",
               {
                  "x": 0.5
               },
               "2,4",
               "2,2",
               "2,1",
               {
                  "x": 7
               },
               "7,4",
               "7,2",
               "7,1",
               {
                  "x": 0.5
               },
               "8,4",
               "8,2",
               "8,1"
            ],
            [
               {
                  "y": -0.5,
                  "x": 1
               },
               "4,3",
               {
                  "x": 7.5
               },
               "1,3",
               {
                  "x": 4
               },
               "6,3",
               {
                  "x": 7.5
               },
               "9,3"
            ],
            [
               {
                  "y": -0.5,
                  "x": 3.5
               },
               "3,0",
               {
                  "x": 2.5
               },
               "2,0",
               {
                  "x": 9
               },
               "7,0",
               {
                  "x": 2.5
               },
               "8,0"
            ],
            [
               {
                  "y": -0.5
               },
               "4,4",
               "4,2",
               "4,1",
               {
                  "x": 5.5
               },
               "1,4",
               "1,2",
               "1,1",
               {
                  "x": 2
               },
               "6,4",
               "6,2",
               "6,1",
               {
                  "x": 5.5
               },
               "9,4",
               "9,2",
               "9,1"
            ],
            [
               {
                  "x": 1
               },
               "4,0",
               {
                  "x": 7.5
               },
               "1,0",
               {
                  "x": 4
               },
               "6,0",
               {
                  "x": 7.5
               },
               "9,0"
            ],
            [
               {
                  "y": 0.5,
                  "x": 7.9,
                  "w": 1.5
               },
               "0,3",
               {
                  "x": 0.1
               },
               "0,5",
               {
                  "x": 0.1,
                  "w": 1.5
               },
               "0,1",
               {
                  "x": 0.8,
                  "w": 1.5
               },
               "5,1",
               {
                  "x": 0.1
               },
               "5,5",
               {
                  "x": 0.1,
                  "w": 1.5
               },
               "5,3"
            ],
            [
               {
                  "x": 7.4,
                  "w": 2
               },
               "0,4",
               {
                  "x": 0.1
               },
               "0,2",
               {
                  "x": 0.1,
                  "w": 1.5
               },
               "0,0",
               {
                  "x": 0.8,
                  "w": 1.5
               },
               "5,0",
               {
                  "x": 0.1
               },
               "5,2",
               {
                  "x": 0.1,
                  "w": 2
               },
               "5,4"
            ]
         ]
      }
   },
 "keymap" : [
    [
       "KC_LCTRL",
       "KC_TAB",
       "KC_LSHIFT",
       "KC_ENTER",
       "MO(14)",
       "KC_CAPSLOCK",
       "KC_O",
       "KC_G",
       "KC_F",
       "KC_R",
       "LSFT(KC_QUOTE)",
       "KC_NO",
       "KC_C",
       "KC_T",
       "KC_D",
       "KC_E",
       "KC_GRAVE",
       "KC_NO",
       "KC_X",
       "KC_B",
       "KC_S",
       "KC_W",
       "KC_ESCAPE",
       "KC_NO",
       "KC_Z",
       "KC_LBRACKET",
       "KC_A",
       "KC_Q",
       "KC_DELETE",
       "KC_NO",
       "KC_LALT",
       "KC_BSPACE",
       "MO(4)",
       "KC_SPACE",
       "MO(2)",
       "MO(5)",
       "KC_K",
       "KC_QUOTE",
       "KC_J",
       "KC_U",
       "KC_H",
       "KC_NO",
       "KC_COMMA",
       "LSFT(KC_SCOLON)",
       "KC_K",
       "KC_I",
       "KC_Y",
       "KC_NO",
       "KC_DOT",
       "KC_NO",
       "KC_L",
       "KC_O",
       "KC_N",
       "KC_NO",
       "KC_SLASH",
       "KC_BSLASH",
       "KC_SCOLON",
       "KC_P",
       "KC_RBRACKET",
       "KC_NO"
    ],
    [
       "KC_TRNS",
       "KC_TRNS",
       "KC_TRNS",
       "KC_TRNS",
       "KC_TRNS",
       "KC_TRNS",
       "KC_NO",
       "RGB_VAI",
       "RGB_TOG",
       "KC_NO",
       "RGB_VAD",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "USER07",
       "KC_NO",
       "KC_NO",
       "KC_TRNS",
       "KC_TRNS",
       "KC_TRNS",
       "KC_TRNS",
       "KC_TRNS",
       "KC_TRNS",
       "KC_HOME",
       "KC_NO",
       "KC_LEFT",
       "LCTL_T(KC_LEFT)",
       "KC_NO",
       "KC_NO",
       "KC_PGDOWN",
       "KC_NO",
       "KC_DOWN",
       "LCTL_T(KC_DOWN)",
       "KC_NO",
       "KC_NO",
       "KC_PGUP",
       "KC_NO",
       "KC_UP",
       "LCTL_T(KC_UP)",
       "KC_NO",
       "KC_NO",
       "KC_END",
       "KC_NO",
       "KC_RIGHT",
       "LCTL_T(KC_RIGHT)",
       "KC_NO",
       "KC_NO"
    ],
    [
       "KC_LCTRL",
       "KC_TAB",
       "KC_LSHIFT",
       "KC_ENTER",
       "KC_TRNS",
       "KC_TRNS",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_ESCAPE",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_DELETE",
       "KC_NO",
       "KC_LALT",
       "KC_BSPACE",
       "MO(4)",
       "KC_SPACE",
       "KC_TRNS",
       "KC_TRNS",
       "KC_HOME",
       "KC_END",
       "KC_LEFT",
       "LCTL(KC_LEFT)",
       "KC_HOME",
       "KC_NO",
       "KC_PGDOWN",
       "KC_NO",
       "KC_DOWN",
       "LCTL(KC_DOWN)",
       "KC_NO",
       "KC_NO",
       "KC_PGUP",
       "KC_NO",
       "KC_UP",
       "LCTL(KC_UP)",
       "KC_INSERT",
       "KC_NO",
       "KC_END",
       "KC_NO",
       "KC_RIGHT",
       "LCTL(KC_RIGHT)",
       "KC_NO",
       "KC_NO"
    ],
    [
       "KC_TRNS",
       "KC_TRNS",
       "KC_TRNS",
       "KC_TRNS",
       "KC_TRNS",
       "KC_TRNS",
       "KC_NO",
       "KC_NO",
       "USER04",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_TRNS",
       "KC_TRNS",
       "KC_TRNS",
       "KC_TRNS",
       "KC_TRNS",
       "KC_NO",
       "KC_TRNS",
       "KC_TRNS",
       "KC_TRNS",
       "KC_TRNS",
       "KC_TRNS",
       "KC_TRNS",
       "LCTL(KC_DOWN)",
       "LCTL(KC_RIGHT)",
       "KC_LEFT",
       "LCTL(KC_UP)",
       "LCTL(KC_LEFT)",
       "KC_NO",
       "KC_MS_D",
       "KC_MS_R",
       "KC_UP",
       "KC_MS_U",
       "KC_MS_L",
       "KC_NO",
       "KC_WH_D",
       "KC_WH_R",
       "KC_DOWN",
       "KC_WH_U",
       "KC_WH_L",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_RIGHT",
       "KC_NO",
       "KC_NO",
       "KC_NO"
    ],
    [
       "KC_LCTRL",
       "KC_TAB",
       "KC_LSHIFT",
       "KC_ENTER",
       "KC_TRNS",
       "KC_TRNS",
       "KC_MINUS",
       "KC_5",
       "KC_4",
       "LSFT(KC_4)",
       "KC_SLASH",
       "KC_NO",
       "LSFT(KC_5)",
       "LSFT(KC_DOT)",
       "KC_3",
       "LSFT(KC_3)",
       "LSFT(KC_COMMA)",
       "KC_NO",
       "KC_X",
       "KC_NO",
       "KC_2",
       "LSFT(KC_2)",
       "KC_ESCAPE",
       "KC_NO",
       "KC_EQUAL",
       "LSFT(KC_GRAVE)",
       "KC_1",
       "LSFT(KC_1)",
       "KC_DELETE",
       "KC_NO",
       "KC_LALT",
       "KC_BSPACE",
       "MO(4)",
       "KC_SPACE",
       "KC_TRNS",
       "KC_TRNS",
       "KC_KP_PLUS",
       "LSFT(KC_MINUS)",
       "KC_7",
       "LSFT(KC_7)",
       "KC_6",
       "KC_NO",
       "KC_COMMA",
       "LSFT(KC_SCOLON)",
       "KC_8",
       "KC_KP_ASTERISK",
       "LSFT(KC_6)",
       "KC_NO",
       "KC_DOT",
       "KC_LGUI",
       "KC_9",
       "LSFT(KC_9)",
       "KC_SCOLON",
       "KC_NO",
       "LSFT(KC_SLASH)",
       "KC_NO",
       "KC_0",
       "LSFT(KC_0)",
       "KC_RBRACKET",
       "KC_NO"
    ],
    [
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_F14",
       "KC_F5",
       "KC_F4",
       "KC_F24",
       "KC_F15",
       "KC_NO",
       "KC_F13",
       "KC_NO",
       "KC_F3",
       "KC_F23",
       "KC_NO",
       "KC_NO",
       "KC_F12",
       "KC_NO",
       "KC_F2",
       "KC_F22",
       "KC_NO",
       "KC_NO",
       "KC_F11",
       "KC_NO",
       "KC_F1",
       "KC_F21",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_F17",
       "KC_F16",
       "KC_F7",
       "KC_NO",
       "KC_F6",
       "KC_NO",
       "KC_F18",
       "KC_NO",
       "KC_F8",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_F19",
       "KC_NO",
       "KC_F9",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_F20",
       "KC_NO",
       "KC_F10",
       "KC_NO",
       "KC_NO",
       "KC_NO"
    ],
    [
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "MO(6)",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO"
    ],
    [
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO"
    ],
    [
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO"
    ],
    [
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO"
    ],
    [
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO"
    ],
    [
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO"
    ],
    [
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO"
    ],
    [
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO"
    ],
    [
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "LCTL(KC_4)",
       "LALT(KC_5)",
       "LALT(KC_4)",
       "LCTL(KC_8)",
       "KC_NO",
       "KC_NO",
       "LCTL(KC_3)",
       "LCTL(KC_TAB)",
       "LALT(KC_3)",
       "LCTL(KC_7)",
       "C_S(KC_TAB)",
       "KC_NO",
       "LCTL(KC_2)",
       "KC_NO",
       "LALT(KC_2)",
       "LCTL(KC_6)",
       "KC_NO",
       "KC_NO",
       "LCTL(KC_1)",
       "LCTL(KC_9)",
       "LALT(KC_1)",
       "LCTL(KC_5)",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO",
       "KC_NO"
    ],
    [
       "KC_TRNS",
       "KC_BTN2",
       "KC_TRNS",
       "KC_BTN1",
       "KC_TRNS",
       "KC_TRNS",
       "USER04",
       "KC_TRNS",
       "KC_BTN1",
       "KC_TRNS",
       "KC_TRNS",
       "KC_NO",
       "KC_BTN3",
       "KC_TRNS",
       "KC_BTN3",
       "KC_TRNS",
       "KC_TRNS",
       "KC_NO",
       "KC_BTN2",
       "KC_TRNS",
       "KC_BTN2",
       "KC_TRNS",
       "KC_TRNS",
       "KC_NO",
       "USER14",
       "KC_TRNS",
       "USER13",
       "KC_TRNS",
       "KC_TRNS",
       "KC_NO",
       "KC_TRNS",
       "KC_BTN2",
       "KC_TRNS",
       "KC_BTN1",
       "KC_TRNS",
       "KC_BTN1",
       "KC_BTN1",
       "KC_TRNS",
       "KC_TRNS",
       "KC_TRNS",
       "KC_TRNS",
       "KC_NO",
       "KC_BTN2",
       "KC_TRNS",
       "KC_TRNS",
       "KC_TRNS",
       "KC_TRNS",
       "KC_NO",
       "KC_BTN3",
       "KC_TRNS",
       "KC_TRNS",
       "KC_TRNS",
       "KC_TRNS",
       "KC_NO",
       "KC_TRNS",
       "KC_NO",
       "KC_NO",
       "KC_TRNS",
       "KC_TRNS",
       "KC_NO"
    ]
 ],
 "layers" : 16,
 "macro_count" : 50,
 "macros" : [
    {
       "actions" : [],
       "mid" : 0
    },
    {
       "actions" : [],
       "mid" : 1
    },
    {
       "actions" : [],
       "mid" : 2
    },
    {
       "actions" : [],
       "mid" : 3
    },
    {
       "actions" : [],
       "mid" : 4
    },
    {
       "actions" : [],
       "mid" : 5
    },
    {
       "actions" : [],
       "mid" : 6
    },
    {
       "actions" : [],
       "mid" : 7
    },
    {
       "actions" : [],
       "mid" : 8
    },
    {
       "actions" : [],
       "mid" : 9
    },
    {
       "actions" : [],
       "mid" : 10
    },
    {
       "actions" : [],
       "mid" : 11
    },
    {
       "actions" : [],
       "mid" : 12
    },
    {
       "actions" : [],
       "mid" : 13
    },
    {
       "actions" : [],
       "mid" : 14
    },
    {
       "actions" : [],
       "mid" : 15
    },
    {
       "actions" : [],
       "mid" : 16
    },
    {
       "actions" : [],
       "mid" : 17
    },
    {
       "actions" : [],
       "mid" : 18
    },
    {
       "actions" : [],
       "mid" : 19
    },
    {
       "actions" : [],
       "mid" : 20
    },
    {
       "actions" : [],
       "mid" : 21
    },
    {
       "actions" : [],
       "mid" : 22
    },
    {
       "actions" : [],
       "mid" : 23
    },
    {
       "actions" : [],
       "mid" : 24
    },
    {
       "actions" : [],
       "mid" : 25
    },
    {
       "actions" : [],
       "mid" : 26
    },
    {
       "actions" : [],
       "mid" : 27
    },
    {
       "actions" : [],
       "mid" : 28
    },
    {
       "actions" : [],
       "mid" : 29
    },
    {
       "actions" : [],
       "mid" : 30
    },
    {
       "actions" : [],
       "mid" : 31
    },
    {
       "actions" : [],
       "mid" : 32
    },
    {
       "actions" : [],
       "mid" : 33
    },
    {
       "actions" : [],
       "mid" : 34
    },
    {
       "actions" : [],
       "mid" : 35
    },
    {
       "actions" : [],
       "mid" : 36
    },
    {
       "actions" : [],
       "mid" : 37
    },
    {
       "actions" : [],
       "mid" : 38
    },
    {
       "actions" : [],
       "mid" : 39
    },
    {
       "actions" : [],
       "mid" : 40
    },
    {
       "actions" : [],
       "mid" : 41
    },
    {
       "actions" : [],
       "mid" : 42
    },
    {
       "actions" : [],
       "mid" : 43
    },
    {
       "actions" : [],
       "mid" : 44
    },
    {
       "actions" : [],
       "mid" : 45
    },
    {
       "actions" : [],
       "mid" : 46
    },
    {
       "actions" : [],
       "mid" : 47
    },
    {
       "actions" : [],
       "mid" : 48
    },
    {
       "actions" : [],
       "mid" : 49
    }
 ],
 "macros_size" : 795,
 "rows" : 10,
 "settings" : {
    "1" : 0,
    "10" : 20,
    "11" : 8,
    "12" : 15,
    "13" : 40,
    "14" : 10,
    "15" : 80,
    "16" : 8,
    "17" : 40,
    "18" : 0,
    "19" : 80,
    "2" : 50,
    "20" : 5,
    "21" : 138,
    "3" : 0,
    "4" : 175,
    "5" : 5,
    "6" : 5800,
    "7" : 280,
    "8" : 0,
    "9" : 30
 },
 "tapdance_count" : 50,
 "tapdances" : [
    {
       "doubletap" : "KC_NO",
       "hold" : "KC_NO",
       "tap" : "KC_NO",
       "taphold" : "KC_NO",
       "tapms" : 200,
       "tdid" : 0
    },
    {
       "doubletap" : "KC_NO",
       "hold" : "KC_NO(1)",
       "tap" : "KC_NO(0)",
       "taphold" : "KC_NO",
       "tapms" : 200,
       "tdid" : 1
    },
    {
       "doubletap" : "KC_NO",
       "hold" : "KC_NO",
       "tap" : "KC_NO",
       "taphold" : "KC_NO",
       "tapms" : 200,
       "tdid" : 2
    },
    {
       "doubletap" : "KC_NO",
       "hold" : "KC_NO",
       "tap" : "KC_NO",
       "taphold" : "KC_NO",
       "tapms" : 200,
       "tdid" : 3
    },
    {
       "doubletap" : "KC_NO",
       "hold" : "KC_NO",
       "tap" : "KC_C",
       "taphold" : "KC_NO",
       "tapms" : 200,
       "tdid" : 4
    },
    {
       "doubletap" : "KC_NO",
       "hold" : "KC_NO",
       "tap" : "KC_NO",
       "taphold" : "KC_NO",
       "tapms" : 200,
       "tdid" : 5
    },
    {
       "doubletap" : "KC_NO",
       "hold" : "KC_NO",
       "tap" : "KC_NO",
       "taphold" : "KC_NO",
       "tapms" : 200,
       "tdid" : 6
    },
    {
       "doubletap" : "KC_NO",
       "hold" : "KC_NO",
       "tap" : "KC_NO",
       "taphold" : "KC_NO",
       "tapms" : 200,
       "tdid" : 7
    },
    {
       "doubletap" : "KC_NO",
       "hold" : "KC_NO",
       "tap" : "KC_NO",
       "taphold" : "KC_NO",
       "tapms" : 200,
       "tdid" : 8
    },
    {
       "doubletap" : "KC_NO",
       "hold" : "KC_NO",
       "tap" : "KC_NO",
       "taphold" : "KC_NO",
       "tapms" : 200,
       "tdid" : 9
    },
    {
       "doubletap" : "KC_NO",
       "hold" : "KC_NO",
       "tap" : "KC_NO",
       "taphold" : "KC_NO",
       "tapms" : 200,
       "tdid" : 10
    },
    {
       "doubletap" : "KC_NO",
       "hold" : "KC_NO",
       "tap" : "KC_NO",
       "taphold" : "KC_NO",
       "tapms" : 200,
       "tdid" : 11
    },
    {
       "doubletap" : "KC_NO",
       "hold" : "KC_NO",
       "tap" : "KC_NO",
       "taphold" : "KC_NO",
       "tapms" : 200,
       "tdid" : 12
    },
    {
       "doubletap" : "KC_NO",
       "hold" : "KC_NO",
       "tap" : "KC_NO",
       "taphold" : "KC_NO",
       "tapms" : 200,
       "tdid" : 13
    },
    {
       "doubletap" : "KC_NO",
       "hold" : "KC_NO",
       "tap" : "KC_NO",
       "taphold" : "KC_NO",
       "tapms" : 200,
       "tdid" : 14
    },
    {
       "doubletap" : "KC_NO",
       "hold" : "KC_NO",
       "tap" : "KC_NO",
       "taphold" : "KC_NO",
       "tapms" : 200,
       "tdid" : 15
    },
    {
       "doubletap" : "KC_NO",
       "hold" : "KC_NO",
       "tap" : "KC_NO",
       "taphold" : "KC_NO",
       "tapms" : 200,
       "tdid" : 16
    },
    {
       "doubletap" : "KC_NO",
       "hold" : "KC_NO",
       "tap" : "KC_NO",
       "taphold" : "KC_NO",
       "tapms" : 200,
       "tdid" : 17
    },
    {
       "doubletap" : "KC_NO",
       "hold" : "KC_NO",
       "tap" : "KC_NO",
       "taphold" : "KC_NO",
       "tapms" : 200,
       "tdid" : 18
    },
    {
       "doubletap" : "KC_NO",
       "hold" : "KC_NO",
       "tap" : "KC_NO",
       "taphold" : "KC_NO",
       "tapms" : 200,
       "tdid" : 19
    },
    {
       "doubletap" : "KC_NO",
       "hold" : "KC_NO",
       "tap" : "KC_NO",
       "taphold" : "KC_NO",
       "tapms" : 200,
       "tdid" : 20
    },
    {
       "doubletap" : "KC_NO",
       "hold" : "KC_NO",
       "tap" : "KC_NO",
       "taphold" : "KC_NO",
       "tapms" : 200,
       "tdid" : 21
    },
    {
       "doubletap" : "KC_G",
       "hold" : "KC_F",
       "tap" : "KC_A",
       "taphold" : "KC_C",
       "tapms" : 200,
       "tdid" : 22
    },
    {
       "doubletap" : "KC_NO",
       "hold" : "KC_NO",
       "tap" : "KC_NO",
       "taphold" : "KC_NO",
       "tapms" : 200,
       "tdid" : 23
    },
    {
       "doubletap" : "KC_NO",
       "hold" : "KC_NO",
       "tap" : "KC_NO",
       "taphold" : "KC_NO",
       "tapms" : 200,
       "tdid" : 24
    },
    {
       "doubletap" : "KC_NO",
       "hold" : "KC_NO",
       "tap" : "KC_NO",
       "taphold" : "KC_NO",
       "tapms" : 200,
       "tdid" : 25
    },
    {
       "doubletap" : "KC_NO",
       "hold" : "KC_NO",
       "tap" : "KC_NO",
       "taphold" : "KC_NO",
       "tapms" : 200,
       "tdid" : 26
    },
    {
       "doubletap" : "KC_NO",
       "hold" : "KC_NO",
       "tap" : "KC_NO",
       "taphold" : "KC_NO",
       "tapms" : 200,
       "tdid" : 27
    },
    {
       "doubletap" : "KC_NO",
       "hold" : "KC_NO",
       "tap" : "KC_NO",
       "taphold" : "KC_NO",
       "tapms" : 200,
       "tdid" : 28
    },
    {
       "doubletap" : "KC_NO",
       "hold" : "KC_NO",
       "tap" : "KC_NO",
       "taphold" : "KC_NO",
       "tapms" : 200,
       "tdid" : 29
    },
    {
       "doubletap" : "KC_NO",
       "hold" : "KC_NO",
       "tap" : "KC_NO",
       "taphold" : "KC_NO",
       "tapms" : 200,
       "tdid" : 30
    },
    {
       "doubletap" : "KC_NO",
       "hold" : "KC_NO",
       "tap" : "KC_NO",
       "taphold" : "KC_NO",
       "tapms" : 200,
       "tdid" : 31
    },
    {
       "doubletap" : "KC_NO",
       "hold" : "KC_NO",
       "tap" : "KC_NO",
       "taphold" : "KC_NO",
       "tapms" : 200,
       "tdid" : 32
    },
    {
       "doubletap" : "KC_NO",
       "hold" : "KC_NO",
       "tap" : "KC_NO",
       "taphold" : "KC_NO",
       "tapms" : 200,
       "tdid" : 33
    },
    {
       "doubletap" : "KC_NO",
       "hold" : "KC_NO",
       "tap" : "KC_NO",
       "taphold" : "KC_NO",
       "tapms" : 200,
       "tdid" : 34
    },
    {
       "doubletap" : "KC_NO",
       "hold" : "KC_NO",
       "tap" : "KC_NO",
       "taphold" : "KC_NO",
       "tapms" : 200,
       "tdid" : 35
    },
    {
       "doubletap" : "KC_NO",
       "hold" : "KC_NO",
       "tap" : "KC_NO",
       "taphold" : "KC_NO",
       "tapms" : 200,
       "tdid" : 36
    },
    {
       "doubletap" : "KC_NO",
       "hold" : "KC_NO",
       "tap" : "KC_NO",
       "taphold" : "KC_NO",
       "tapms" : 200,
       "tdid" : 37
    },
    {
       "doubletap" : "KC_NO",
       "hold" : "KC_NO",
       "tap" : "KC_NO",
       "taphold" : "KC_NO",
       "tapms" : 200,
       "tdid" : 38
    },
    {
       "doubletap" : "KC_NO",
       "hold" : "KC_NO",
       "tap" : "KC_NO",
       "taphold" : "KC_NO",
       "tapms" : 200,
       "tdid" : 39
    },
    {
       "doubletap" : "KC_NO",
       "hold" : "KC_NO",
       "tap" : "KC_NO",
       "taphold" : "KC_NO",
       "tapms" : 200,
       "tdid" : 40
    },
    {
       "doubletap" : "KC_NO",
       "hold" : "KC_NO",
       "tap" : "KC_NO",
       "taphold" : "KC_NO",
       "tapms" : 200,
       "tdid" : 41
    },
    {
       "doubletap" : "KC_NO",
       "hold" : "KC_NO",
       "tap" : "KC_NO",
       "taphold" : "KC_NO",
       "tapms" : 200,
       "tdid" : 42
    },
    {
       "doubletap" : "KC_NO",
       "hold" : "KC_NO",
       "tap" : "KC_NO",
       "taphold" : "KC_NO",
       "tapms" : 200,
       "tdid" : 43
    },
    {
       "doubletap" : "KC_NO",
       "hold" : "KC_NO",
       "tap" : "KC_NO",
       "taphold" : "KC_NO",
       "tapms" : 200,
       "tdid" : 44
    },
    {
       "doubletap" : "KC_NO",
       "hold" : "KC_NO",
       "tap" : "KC_NO",
       "taphold" : "KC_NO",
       "tapms" : 200,
       "tdid" : 45
    },
    {
       "doubletap" : "KC_NO",
       "hold" : "KC_NO",
       "tap" : "KC_NO",
       "taphold" : "KC_NO",
       "tapms" : 200,
       "tdid" : 46
    },
    {
       "doubletap" : "KC_NO",
       "hold" : "KC_NO",
       "tap" : "KC_NO",
       "taphold" : "KC_NO",
       "tapms" : 200,
       "tdid" : 47
    },
    {
       "doubletap" : "KC_NO",
       "hold" : "KC_NO",
       "tap" : "KC_NO",
       "taphold" : "KC_NO",
       "tapms" : 200,
       "tdid" : 48
    },
    {
       "doubletap" : "KC_NO",
       "hold" : "KC_NO",
       "tap" : "KC_NO",
       "taphold" : "KC_NO",
       "tapms" : 200,
       "tdid" : 49
    }
 ],
 "via_proto" : 9,
 "vial_proto" : 6
};
